plugins {
  id "org.owasp.dependencycheck" version "12.2.0"
  id "java"
  id 'application'
  id "com.github.spotbugs" version "6.5.4"
}

repositories {
	 // Using public maven central for the course work
     mavenCentral()  
     // For gradle tooling api
     maven { url = 'https://repo.gradle.org/gradle/libs-releases' }
}

dependencies {
   implementation 'org.json:json:20251224'
   implementation 'org.apache.logging.log4j:log4j-api:2.25.4'
   implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
   implementation 'org.slf4j:slf4j-simple:2.0.18'
   testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
   implementation 'org.gradle:gradle-tooling-api:9.2.1'
   implementation 'com.github.spotbugs:spotbugs:4.9.8'
   implementation 'com.github.spotbugs:spotbugs-annotations:4.9.8'
   implementation 'org.owasp:dependency-check-core:12.2.0'
   implementation 'org.freemarker:freemarker:2.3.34'
} 

tasks.register('copyDependencies', Copy) {
    from configurations.runtimeClasspath
    into "$buildDir/libs-deps"
}

dependencyCheck {
    autoUpdate = false
    format = 'ALL'
}

sourceSets {
	test {
		java {
			srcDirs = ["src/test/java"]
		}
	}
}

application {
    mainClass = 'Cli.DependencyVulnerabilityScanner'
}

jar {
  manifest {
    attributes 'Main-Class': application.mainClass
  }
}

distributions {
    main {
        distributionBaseName = 'DependencyVulnerabilityScanner'
        distributionClassifier = 'Exercise-Work'
        contents {
        	into('config') {
            	from 'config'
            }
        }
    }
}
