# Use this to state whether to use NVD API for vulnerability search.
# Accepted values:
#	true
#	false
# Default value: false
scanForVulnerabilities=true
# Use this to state whether to use static code analysis.
# Accepted values:
#	true
#	false
# Default value: false
staticCodeAnalysis=true
# If you want to use vulnerability search, please provide your own NVD API key.
# Accepted values:
#  NVD API key
# Default value: empty
nvdApiKey="45cb8872-65c8-4fcc-a4b7-27e32ae58654"