# Use this to state whether to use NVD API for vulnerability search.
# Accepted values:
#	true
#	false
# Default value: false
scanForVulnerabilities=true
# Use this to state whether to use static code analysis.
# Accepted values:
#	true
#	false
# Default value: false
staticCodeAnalysis=true
# If you want to use vulnerability search, please provide your own NVD API key.
# Accepted values:
#  NVD API key
# Default value: empty
nvdApiKey=
# Specify the location in which the dependency-check HTML report is saved.
# Accepted values:
#  Paths written either C:/Users/testUser/results or C:\\Users\\testUser\\results
# Default value: empty
dependencyReportPath=